import { isValidElement, type ReactElement } from "react";
import { ConcurrentRoot } from "react-reconciler/constants";

import { Tag } from "./constants";
import { measureEnd, measureStart } from "./performance";
import type { Container, TransformHiddenInstanceProps } from "./reconciler";
import { TestReconciler } from "./reconciler";
import { TestInstance } from "./test-instance";

// Refs:
// https://github.com/facebook/react/blob/main/packages/react-test-renderer/src/ReactFiberConfigTestHost.js
// https://github.com/facebook/react/blob/main/packages/react-noop-renderer/src/createReactNoop.js
// https://github.com/facebook/react/blob/main/packages/react-native-renderer/src/ReactFiberConfigFabric.js

const defaultOnUncaughtError = (error: unknown, errorInfo: ErrorInfo) => {
  console.error("Uncaught error:", error, errorInfo);
};
const defaultOnCaughtError = (error: unknown, errorInfo: ErrorInfo) => {
  console.error("Caught error:", error, errorInfo);
};
const defaultOnRecoverableError = (error: unknown, errorInfo: ErrorInfo) => {
  console.error("Recoverable error:", error, errorInfo);
};
const defaultOnDefaultTransitionIndicator = () => {};

/**
 * Options for configuring the test renderer root.
 */
export type RootOptions = {
  /** Types of host components that are allowed to contain text nodes. Trying to render text outside of these components will throw an error. */
  textComponentTypes?: string[];

  /**
   * Host component types to display to users in the error message when they try to render text outside of `textComponentTypes`.
   * Defaults to `textComponentTypes`, but you may want to override the components mentioned in the error message.
   */
  publicTextComponentTypes?: string[];

  /**
   * Transform props when React marks a host instance as hidden (e.g. during Suspense fallback).
   * Receives `{ props, type }` and should return a new props object.
   * Avoid mutating the provided `props` object.
   */
  transformHiddenInstanceProps?: TransformHiddenInstanceProps;

  /** Callback called when React catches an error in an Error Boundary. Called with the error caught by the Error Boundary, and an errorInfo object containing the componentStack. */
  onCaughtError?: ErrorHandler;

  /** Callback called when an error is thrown and not caught by an Error Boundary. Called with the error that was thrown, and an errorInfo object containing the componentStack. */
  onUncaughtError?: ErrorHandler;

  /** Callback called when React automatically recovers from errors. Called with an error React throws, and an errorInfo object containing the componentStack. Some recoverable errors may include the original error cause as error.cause. */
  onRecoverableError?: ErrorHandler;

  /** A string prefix React uses for IDs generated by useId. Useful to avoid conflicts when using multiple roots on the same page. */
  identifierPrefix?: string;

  /** Enable React Strict Mode. */
  isStrictMode?: boolean;
};

/** Callback for handling React errors. */
export type ErrorHandler = (error: unknown, errorInfo: ErrorInfo) => void;

/** Error information provided to error handlers. */
export type ErrorInfo = {
  componentStack?: string;
};

/**
 * Root instance returned by createRoot. Provides methods to render and unmount components.
 */
export type Root = {
  /** Render a React element into the root. Must be called within act(). */
  render: (element: ReactElement) => void;
  /** Unmount the root and clean up. Must be called within act(). */
  unmount: () => void;
  /** The root container element. */
  container: TestInstance;
};

/**
 * Create a new test renderer root instance.
 *
 * @param options - Optional configuration for the renderer.
 * @returns A Root instance with render, unmount, and container properties.
 */
export function createRoot(options?: RootOptions): Root {
  measureStart("createRoot");

  let container: Container | null = {
    tag: Tag.Container,
    parent: null,
    children: [],
    isHidden: false,
    config: {
      textComponentTypes: options?.textComponentTypes,
      publicTextComponentTypes: options?.publicTextComponentTypes,
      transformHiddenInstanceProps: options?.transformHiddenInstanceProps,
    },
  };

  // @types/react-reconciler types don't fully match react-reconciler's actual Flow types.
  // The return type is correct at runtime but TypeScript can't verify it statically.
  // Correctness is verified through tests.
  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  let containerFiber = TestReconciler.createContainer(
    container,
    ConcurrentRoot,
    null, // hydrationCallbacks
    options?.isStrictMode ?? false,
    false, // concurrentUpdatesByDefaultOverride
    options?.identifierPrefix ?? "",
    options?.onUncaughtError ?? defaultOnUncaughtError,
    options?.onCaughtError ?? defaultOnCaughtError,
    options?.onRecoverableError ?? defaultOnRecoverableError,
    defaultOnDefaultTransitionIndicator,
    null, // transitionCallbacks
  );

  measureEnd("createRoot");

  const render = (element: ReactElement) => {
    if (containerFiber == null) {
      throw new Error("Cannot render after unmount");
    }

    measureStart("render");
    let elementType = "<invalid>";
    try {
      assertValidRootElement(element);
      elementType = String(element.type);
      TestReconciler.updateContainer(element, containerFiber, null, null);
    } finally {
      measureEnd("render", { elementType });
    }
  };

  const unmount = () => {
    if (container == null) {
      return;
    }

    measureStart("unmount");
    try {
      TestReconciler.updateContainer(null, containerFiber, null, null);
    } finally {
      measureEnd("unmount");
    }

    containerFiber = null;
    container = null;
  };

  return {
    render,
    unmount,
    get container(): TestInstance {
      if (container == null) {
        throw new Error("Cannot access .container on unmounted test renderer");
      }

      return TestInstance.fromInstance(container);
    },
  };
}

function assertValidRootElement(element: ReactElement): void {
  if (isValidElement(element)) {
    return;
  }

  throw new Error(
    `root.render(...) expects a React element. Fragments are supported, but received ${formatInvalidRootValue(
      element,
    )}.`,
  );
}

function formatInvalidRootValue(value: unknown): string {
  if (value === null) {
    return "null";
  }

  if (Array.isArray(value)) {
    return "an array";
  }

  switch (typeof value) {
    case "string":
      return "a string";
    case "number":
      return "a number";
    case "boolean":
      return "a boolean";
    case "undefined":
      return "undefined";
    default:
      return `a ${typeof value}`;
  }
}
