name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup deps
        uses: ./.github/actions/setup

      - name: Build
        run: bun run build

      - name: Run format
        run: bun run format:check

      - name: Run linter
        run: bun run lint

      - name: Run typecheck
        run: bun run typecheck

      - name: Run tests
        run: bun run test:ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  test-react-versions:
    name: Test React ${{ matrix.react-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react-version: ["~19.0.0", "~19.1.0", "~19.2.0", "latest", "next"]
    steps:
      - uses: actions/checkout@v5

      - name: Setup deps
        uses: ./.github/actions/setup

      - name: Install React ${{ matrix.react-version }}
        run: bun add -d react@${{ matrix.react-version }}

      - name: Run typecheck
        run: bun run typecheck

      - name: Run tests
        run: bun run test:ci
